### ISSUE TITLE
Fails to train on GPU

### ISSUE THREAD

**Issue by sixftninja** [naruya/VaxNeRF#1]
Hi,

Congrats on your work! I'm trying to Vax the lego dataset from NeRF on a GCP vm with A100. I have followed instructions from JaxNeRF repo and installed cudatoolkit 11.0.221 through Conda. The visuals hull was created successfully but when I run training I get the following message:
```E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error```
```140511409292096 xla_bridge.py:243] Unable to initialize backend 'gpu': FAILED_PRECONDITION: No visible GPU devices```

Here's the output of nvidia-smi:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P0    44W / 400W |    111MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1178      G   /usr/lib/xorg/Xorg                 95MiB |
|    0   N/A  N/A      1218      G   /usr/bin/gnome-shell               14MiB |
+-----------------------------------------------------------------------------+
```
This driver and CUDA  is what I've manually installed but pasted the output here to show that nvidia-smi works. 
For VaxNeRF I've installed cudatoolkit and cud (8.2) through Conda. 

I want to train on my own data after I've trained it on lego. 
Will it be possible for you to add instructions to achieve the same?

Thanks!

**Comment by naruya** [comment]
Hi, Thanks for finding our research!!

I'm sorry for the inconvenience.
This problem seems to be caused by using multi-processing in the code, which may or may not happen depending on the version of jax. Actually, the first 500 steps are used to optimize the number of sample points to be input to MLP. This process is done in a multi-process (to prevent memory leaks), and somehow the multi-process may not recognize the GPU.

I'd like you to try running the code as is until I resolve this issue. It is true that the first 500 steps are quite slow, but it takes only a few minutes, and after that, I can see that it starts fast learning using the GPU (and Vax optimization!).

Or you can find the fixed version of the code [here](https://github.com/naruya/mipnerf/blob/main/train.py). (This is Vax'ed MipNeRF though).

**Comment by sixftninja** [comment]
Hi Thanks for your response. I tried continuing training but it's still failing. Here's the entire error message:

```
I1226 14:30:41.174754 139924317341504 xla_bridge.py:243] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I1226 14:30:41.302836 139924317341504 xla_bridge.py:243] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py:412: UserWarning: jax.host_id has been renamed to jax.process_index. This alias will eventually be removed; please update your code.
  warnings.warn(
/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py:425: UserWarning: jax.host_count has been renamed to jax.process_count. This alias will eventually be removed; please update your code.
  warnings.warn(
2021-12-26 14:31:20.360912: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2086] Execution of replica 0 failed: INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    app.run(main)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "train.py", line 312, in main
    train(FLAGS.max_steps)
  File "train.py", line 145, in train
    rng, key = random.split(rng)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/random.py", line 190, in split
    return _return_prng_keys(wrapped, _split(key, num))
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/random.py", line 176, in _split
    return key._split(num)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/prng.py", line 191, in _split
    return PRNGKeyArray(self.impl, self.impl.split(self._keys, num))
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/prng.py", line 439, in threefry_split
    return _threefry_split(key, int(num))  # type: ignore
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/core.py", line 1661, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/core.py", line 1652, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/core.py", line 1664, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/core.py", line 633, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/dispatch.py", line 131, in _xla_call_impl
    out = compiled_fun(*args)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/dispatch.py", line 436, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 316, in <module>
    app.run(main)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "train.py", line 312, in main
    train(FLAGS.max_steps)
  File "train.py", line 145, in train
    rng, key = random.split(rng)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/random.py", line 190, in split
    return _return_prng_keys(wrapped, _split(key, num))
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/random.py", line 176, in _split
    return key._split(num)
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/prng.py", line 191, in _split
    return PRNGKeyArray(self.impl, self.impl.split(self._keys, num))
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/prng.py", line 439, in threefry_split
    return _threefry_split(key, int(num))  # type: ignore
  File "/home/anandaltekar_gmail_com/miniconda3/envs/jaxnerf/lib/python3.8/site-packages/jax/_src/dispatch.py", line 436, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.
```

**Comment by sixftninja** [comment]
I did a fresh install of CUDA 11.5 and cudnn 8.3 and it's training now! but the evaluation takes a really long time. Is that expected?

**Comment by naruya** [comment]
@sixftninja 
Oops, I hadn't seen that error before. Maybe you had better make sure that JaxNeRF works before trying to run it.
But I'm glad to hear that our code worked.  Thanks!!

> but the evaluation takes a really long time. Is that expected?

Yes, our `eval.py` evaluates multiple stored checkpoints to examine the history of NeRF's accuracy. (It takes a lot of time just to evaluate a single checkpoint.) It is recommended to erase all steps in `eval.py` except the step of the checkpoint you want to evaluate and run it.

Also, if you want, you can try [Vax-MipNeRF](https://github.com/naruya/mipnerf), which we just released and updated the README. You can get much better accuracy in the same amount of time, with almost no additional installation, and the code is more refined 😊

![psnr_mip](https://user-images.githubusercontent.com/23403885/147459802-8871f92f-923d-437c-a0a8-79b6077985ab.png)
