### ISSUE TITLE
TypeError: broadcast_to requires ndarray or scalar arguments, got <class 'list'> at position 0.

### ISSUE THREAD

**Issue by naruya** [naruya/VaxNeRF#6]
```
(jaxnerf) ➜  VaxNeRF git:(main) python train.py \
    --config configs/demo \
    --data_dir data/nerf_synthetic/lego \
    --train_dir logs/lego_c64f128 \
    --num_coarse_samples 64 \
    --num_fine_samples 128 \
    --render_every 2500
I0530 19:00:30.947573 140039295452352 xla_bridge.py:330] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I0530 19:00:31.048327 140039295452352 xla_bridge.py:330] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py:501: UserWarning: jax.host_id has been renamed to jax.process_index. This alias will eventually be removed; please update your code.
  warnings.warn(
/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py:514: UserWarning: jax.host_count has been renamed to jax.process_count. This alias will eventually be removed; please update your code.
  warnings.warn(
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    app.run(main)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "train.py", line 312, in main
    train(FLAGS.max_steps)
  File "train.py", line 146, in train
    model, variables = models.get_model(key, dataset.peek(), FLAGS)
  File "/root/workspace/VaxNeRF/nerf/models.py", line 33, in get_model
    return model_dict[args.model](key, example_batch, args)
  File "/root/workspace/VaxNeRF/nerf/models.py", line 322, in construct_nerf
    init_variables = model.init(
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/linen/module.py", line 1224, in init
    _, v_out = self.init_with_output(
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/linen/module.py", line 1191, in init_with_output
    return self.apply(
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/linen/module.py", line 1156, in apply
    return apply(
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/core/scope.py", line 831, in wrapper
    y = fn(root, *args, **kwargs)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/linen/module.py", line 1440, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/linen/transforms.py", line 1239, in wrapped_fn
    return prewrapped_fn(self, *args, **kwargs)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/linen/module.py", line 350, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/flax/linen/module.py", line 648, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/root/workspace/VaxNeRF/nerf/models.py", line 153, in __call__
    comp_rgb, disp, acc, weights = model_utils.volumetric_rendering(
  File "/root/workspace/VaxNeRF/nerf/model_utils.py", line 173, in volumetric_rendering
    jnp.broadcast_to([1e10], z_vals[Ellipsis, :1].shape)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/numpy/util.py", line 345, in _broadcast_to
    _check_arraylike("broadcast_to", arr)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/numpy/util.py", line 298, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: broadcast_to requires ndarray or scalar arguments, got <class 'list'> at position 0.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 316, in <module>
    app.run(main)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "train.py", line 312, in main
    train(FLAGS.max_steps)
  File "train.py", line 146, in train
    model, variables = models.get_model(key, dataset.peek(), FLAGS)
  File "/root/workspace/VaxNeRF/nerf/models.py", line 33, in get_model
    return model_dict[args.model](key, example_batch, args)
  File "/root/workspace/VaxNeRF/nerf/models.py", line 322, in construct_nerf
    init_variables = model.init(
  File "/root/workspace/VaxNeRF/nerf/models.py", line 153, in __call__
    comp_rgb, disp, acc, weights = model_utils.volumetric_rendering(
  File "/root/workspace/VaxNeRF/nerf/model_utils.py", line 173, in volumetric_rendering
    jnp.broadcast_to([1e10], z_vals[Ellipsis, :1].shape)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/numpy/util.py", line 345, in _broadcast_to
    _check_arraylike("broadcast_to", arr)
  File "/root/.pyenv/versions/jaxnerf/lib/python3.8/site-packages/jax/_src/numpy/util.py", line 298, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: broadcast_to requires ndarray or scalar arguments, got <class 'list'> at position 0.
```

**Comment by naruya** [comment]
https://github.com/naruya/VaxNeRF/blob/32307b9c318014baf5b1bf629598e7b215652c7f/nerf/model_utils.py#L173

`jnp.broadcast_to([1e10], z_vals[Ellipsis, :1].shape)`
↓
`jnp.broadcast_to(1e10, z_vals[Ellipsis, :1].shape)`
